name-template: '$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'type:new feature'
  - title: '🔬 Improvements'
    labels:
      - 'type:improvement'
  - title: '🐞 Bug Fixes'
    labels:
      - 'type:bug'
  - title: '⬆️ Dependency Updates'
    labels:
      - 'type:dependencies'
  - title: '👻 Internal changes'
    labels:
      - 'type:internal'

change-template: '* $TITLE (via #$NUMBER) - @$AUTHOR'
template: |
  $CHANGES

  ## 👀 Links

  [Commits since $PREVIOUS_TAG](https://github.com/allure-framework/allure-teamcity/compare/$PREVIOUS_TAG...master)

